### PR TITLE
V2.5.1

### PR DESCRIPTION
**Pull request by scopatz**
Rerender and version bump

### CODE REVIEW

**Comment by scopatz** [comment]
Retriggering appveyor

**Comment by scopatz** [comment]
We know from the previous run that this worked on mac.  Merging rather than waiting for travis.

**Comment by scopatz** [comment]
Or rather we can merge...

**Comment by scopatz** [comment]
@conda-forge/core can this be merged please? Thanks!

**Comment by scopatz** [comment]
Thanks @ocefpaf !

**Comment by ocefpaf** [comment]
No problem! Thanks for the update!

**Pull request merged**
